### ISSUE TITLE
Some uuid questions

### ISSUE THREAD

**Issue by dragonfire1119** [EmadAdly/laravel-uuid#1]
With the uuid isn't there a chance to have users with the same uuid if you have a large database?

Also I've been reading allot about uuid & people have different opinions on if you should keep the auto increment id in the database.

People also bring up about a performance issue with MySQL databases.

Thanks for your time & work on this project.

**Comment by EmadAdly** [comment]
@dragonfire1119 you are welcome 

About repeat it's a very difficult to repeat it. However, you must set the uuid column to be a `unique`.

As for the Incremental you can keeping it along with the uuid as you like, personally I prefer it. in my projects but provided they do not appear in the frontend.

With respect to performance, about my experience it's not there will be effect of significantly, a uuid is 36 characters with dashes and you also will store it in  `char(36)`, also you can make it a `primary key`, This does not make them to be slow.

I recommend reading the following two posts 

[Why Auto Increment Is A Terrible Idea](https://www.clever-cloud.com/blog/engineering/2015/05/20/why-auto-increment-is-a-terrible-idea/)
[Store UUID in an Optimized Way](https://dzone.com/articles/store-uuid-optimized-way)
