### ISSUE TITLE
Primary key other than "id"/ "uuid"

### ISSUE THREAD

**Issue by guilherme90** [EmadAdly/laravel-uuid#10]
Hi, all right?

In my Model, using $primaryKey attributes. I can use this attribute to set column name?

**Comment by EmadAdly** [comment]
if you want to replacing default id with uuid and set the primary key [replacing default id with uuid](https://github.com/EmadAdly/laravel-uuid#replacing-default-id-with-uuid)

or you  ask if you can have more than one primary key ?

**Comment by guilherme90** [comment]
Do not.

My primary key pattern is not only `id`, but the name of the table + id, ie: `user_id`, understood?

**Comment by EmadAdly** [comment]
Why don't you add a unique index, and keep the `id` or `uuid` as primary ? However, you can specify more than one column as the primary key As follows : 
```php
Schema::create('tests', function (Blueprint $table) {
  $table->unsignedInteger('id');
  $table->uuid('uuid');
  $table->string('name');
  $table->integer('user_id');
  $table->timestamps();
  $table->primary(array('id', 'name', 'user_id'));
});
```

**Comment by guilherme90** [comment]
Because there is no need to do this. My bank follows pattern other than `id` or` uuid`. But, there, how can you improve? It's not legal that way.

**Comment by EmadAdly** [comment]
I don't know your app, and you don't explain what is the other pattern used in your bank.

And why the previous way is illegal check the [Laravel docs](https://laravel.com/docs/5.5/migrations#indexes) in the `Available Index types` table, Is actually a composite keys. also you can set it through the `mysql` or `phpmyadmin`.

Please let me close this since it's not actually a bug report.

**Comment by guilherme90** [comment]
I just explained. I'll try again. I want the column name in my user table `user_id` and not `id` /` uuid`, understood now?

**Comment by EmadAdly** [comment]
in `config/uuid.php` file  set the `default_uuid_column` to `user_id`
```php
'default_uuid_column' => 'user_id',
```

and if you make a first time migrate you can build schema like so

```php
        Schema::create('cash_managements', function (Blueprint $table) {
            ...
            $table->uuid('user_id')->unique();
            ...
        });
```
Or if have already table in database
you can change this column to char(36) type and don't forget set as a unique.

i hope this solution will suit you

**Comment by guilherme90** [comment]
It's all right. And I want to use Laravel's modularization system, can I use this configuration file in each module? And if inside my module, I have several templates that represent different tables, how do I do in that case?

Your code has an architecture flaw ;(

**Comment by andreyvital** [comment]
@EmadAdly AFAIK, it doesn't suit. What I believe he's trying to say is... he wants the uuid column to be prefixed with the table name, and if I set it globally through the `config/uuid.php`, each model will have a `user_id` column rather than `cash_id` `something_id` `something_else_id`.

Does that make sense for ya?

**Comment by andreyvital** [comment]
@EmadAdly the simplest solution I thought to resolve this issue would be to interpolate the default column name. So what I ended up doing is `"default_uuid_column" => "{table}_id"` which produces the desired column name.

Could you please review and merge? #11 

Not sure if the code makes sense tho. Also, if you can publish it whenever you merge, that's going to be super.

**Comment by EmadAdly** [comment]
Hey guys! Sorry for delay. I had very busy days. I'll take a look for it as soon as possible.

**Comment by EmadAdly** [comment]
I see it not a big need for this at the moment. and your approach uncommon and it is not good practice.

**Comment by guilherme90** [comment]
I totally disagree with you when you say this is a bad practice, and still says it's an unusual approach. Each one does the modeling of the bank according to its standards. I simply will not use it, and certainly many too, too, because it is very limited in its way of modeling a scheme, or in accordance with the standard laravel style.

Good luck!
