### ISSUE TITLE
downcased UUIDs

### ISSUE THREAD

**Issue by thomhickey** [EmadAdly/laravel-uuid#13]
Hello ... thanks for the great work! Any chance you plan on adding downcased UUIDs perhaps via a config switch? I had to pull the trait into my own code-base just to make the simple change of removing strtoupper and modifying the regex. I believe downcased UUIDs are considered a best practice? I'm happy to do a PR if you don't have the time or inclination.

**Comment by EmadAdly** [comment]
Thanks @thomhickey  you are welcome and PR are also welcome , It is preferred to be switch through the config As you say and to be the default mode lowercase.

**Comment by EmadAdly** [comment]
[updated](https://github.com/EmadAdly/laravel-uuid/commit/8990d35f1784ec6f75cdcfc5a4a50e1283441009)
