### ISSUE TITLE
Add docs for overriding the boot method

### ISSUE THREAD

**Issue by iSWORD** [EmadAdly/laravel-uuid#14]
Hi, thanks for the easy to use package!

I had to modify the boot method in one of my models to add global scopes but then I found out that Uuids were no longer being generated, so I solved it like this:
```php
use Uuids {
    boot as protected uuid_boot;
}
```
instead of:
```php
use Uuids;
```
then in the modified boot method:
```php
protected static function boot()
{
    parent::boot();
    self::uuid_boot();

    // static::addGlobalScope(...);
}
```
Please add this somewhere in the readme/docs/whatever. Thank you!

**Comment by EmadAdly** [comment]
I'd accept a PR with tests that fixes this.
