### ISSUE TITLE
uuid is not saved with pivot

### ISSUE THREAD

**Issue by malekbenelouafi** [EmadAdly/laravel-uuid#18]
When the model has many to many relations, then the UUID is not saved with attach and sync functions.

**Comment by EmadAdly** [comment]
Let me know if this problem is resolved.

**Comment by paulocastellano** [comment]
The issue has closed but... is working with relation table? @EmadAdly @malekbenelouafi

**Comment by zaynbuksh** [comment]
Hi, @EmadAdly @JeffBeltran. Is there a solution to this problem? Can you please reopen this issue?

**Comment by JeffBeltran** [comment]
@zaynbuksh i'm not a maintainer just submitted a change for docs. That being said i'm not aware of this issue as i have only used this package on a test project. Good luck

**Comment by zaynbuksh** [comment]
No worries, Jeff. I’m trying a different UUID solution now :)
