### ISSUE TITLE
Too few arguments error when using this package.

### ISSUE THREAD

**Issue by alexrfan03** [EmadAdly/laravel-uuid#2]
Type error: Too few arguments to function Illuminate\Database\Eloquent\Model::setAttribute(), 1 passed in /Users/user/Code/y/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php on line 519 and exactly 2 expected
in HasAttributes.php line 511
at Model->setAttribute(array()) in HasAttributes.php line 519
at Model->setAttribute('', array()) in Model.php line 1246
at Model->__set('', array()) in Uuids.php line 22
at Staff::Emadadly\LaravelUuid\{closure}(object(Staff)) in Dispatcher.php line 334

**Comment by EmadAdly** [comment]
@alexrfan03 you are welcome

1) Make sure publish the config file
```bash 
php artisan vendor:publish --provider="Emadadly\LaravelUuid\LaravelUuidServiceProvider"
```
2) Set your default_uuid_column  in `config/uuid.php` for example `uuid` also make sure it is the same the name of field in the model and database table

3) Make sure include trait in your model.
```php 
use Illuminate\Database\Eloquent\Model;
use Emadadly\LaravelUuid\Uuids;

class ExampleModel extends Model
{
    use Uuids;
}
```

if there is still a problem, please be send a shots both model and schema.
