### ISSUE TITLE
Automatitly generate uuid for an existing table

### ISSUE THREAD

**Issue by khoude24** [EmadAdly/laravel-uuid#23]
I already have an user table with rows, if I add uuid column, how can I generate uuid to all my rows?

**Comment by djunehor** [comment]
In the case of others, here's a quick fix.

- After installing the package, publish the config `php artisan vendor:publish --provider="Emadadly\LaravelUuid\LaravelUuidServiceProvider"` and set the uuid column if need be.

- Create a migration to add uuid column to `users` table i.e `php artisan make:migration add_uuid_column_to_users_table`.

The `up` method should contain:
```
 Schema::table('users', function (Blueprint $table) {
	if(Schema::hasColumn('users', 'uuid')) {
	  $table->dropColumn(config('uuid.default_uuid_column'));
	}
        });
```

- Run `php artisan migrate`

- Create a Seeder for users table i.e `php artisan db:seed --class=UsersTableSeeder`

- The `run` method should contain:
```
// Eloquent
\App\User::query()->orderBy('id')->chunk(100, function ($users) {
   foreach ($users as $user) {
    $user->{config('uuid.default_uuid_column')} = Uuid::uuid4()->toString();
    $user->save();
   }
 });

// Query builder
$tableName = 'users';
$uuidColumn = config('uuid.default_uuid_column');

\DB::table('users')->orderBy('id')->chunk(100, function ($users) use ($tableName, $uuidColumn) {
   foreach ($users as $user) {
	\DB::table($tableName)
	  ->where('id', $user->id)
	  ->update([$uuidColumn => Uuid::uuid4()->toString()]);
	}
});
```

**Comment by EmadAdly** [comment]
Closing this as this is not an issue about the internals of the package.
Feel free to keep the conversation going.
