### ISSUE TITLE
Recommendation for using ramsey/uuid for generating UUID's

### ISSUE THREAD

**Issue by bhulsman** [EmadAdly/laravel-uuid#3]
Just a suggestion, for improvement of the package.

Laravel uses the https://github.com/ramsey/uuid for generating UUID's: https://github.com/laravel/framework/blob/5.4/composer.json#L28. At least for notifications (https://github.com/laravel/framework/blob/5.4/src/Illuminate/Notifications/NotificationSender.php#L82).

Since ramsey/uuid follows the RFC 4122 specification, that might be better way to generate the UUID's, instead of relying on your own method.

**Comment by EmadAdly** [comment]
@bhulsman  You're welcome,
Thanks for bringing this to my attention. I will do it in the next weekend.

**Comment by EmadAdly** [comment]
new release [v1.2](https://github.com/EmadAdly/laravel-uuid/releases/tag/v1.2)
