### ISSUE TITLE
Documentation suggests both unique and primary index on the id column

### ISSUE THREAD

**Issue by judgej** [EmadAdly/laravel-uuid#31]
In the documentation, this is suggested when using the UUID to replace the normal incrementing ID:

    $table->uuid('id')->unique();
    $table->primary('id');

Would that not create *two* indexes on the table - a unique index, and a primary key index that also happens to be unique? Just the primary index will be sufficient.

The main difference between the two types of index is that a primary key cannot hold a null but a unique index can (unless you are using MS SQL, which treats a null as a unique value, rather than being ignored, as it should be IMO).

**Comment by EmadAdly** [comment]
Actually exactly, it's depending on your the application.
