### ISSUE TITLE
Creating new record manually setting primary UUID

### ISSUE THREAD

**Issue by markaduffy** [EmadAdly/laravel-uuid#32]
Can you tell me how I might do this.  I have a backup database that I want to insert records with id/UUID primary key set using eloquent create() method.  Basically, I want to export UUID to new database using same model, without generating new UUID

```
class User extends Model
{
    use Uuids;

    public $incrementing = false;

    protected $fillable = [
        'id',
```

**Comment by EmadAdly** [comment]
I guess after removing `use Uuids` you will all normally.
