### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by anx-mwutte** [EmadAdly/laravel-uuid#38]
Hi, is it possible to support the new PHP 8?
Thank you very much in advance!

**Comment by maximal** [comment]
@EmadAdly, seems like it’s just `"php": "~5.6|~7.0"` → `"php": "~5.6|~7.0|^8.0"` in `composer.json`’s `require` section.

**Comment by EmadAdly** [comment]
Done @maximal @anx-mwutte

**Comment by ahmed-alaa** [comment]
@EmadAdly i'm not sure if it's done.

https://packagist.org/packages/emadadly/laravel-uuid#v1.3.2 -> php: ~5.6|~7.0 as well as tried to use it with composer require php 8, shows that package doesn't support it.

with https://packagist.org/packages/emadadly/laravel-uuid#dev-master tag -> works as expected

if possible to check ;) Thanks :D
