### ISSUE TITLE
Laravel 9 update not published

### ISSUE THREAD

**Issue by duffn** [EmadAdly/laravel-uuid#44]
There is a commit here to update the package to support Laravel 9 https://github.com/EmadAdly/laravel-uuid/commit/2b7456e42d75f4c48082b92b77b9f658d3c6eee0, however this update has not be published in a new package version https://packagist.org/packages/emadadly/laravel-uuid

Thanks.

**Comment by b14r** [comment]
Yeah, whats up with that

**Comment by EmadAdly** [comment]
already done
