### ISSUE TITLE
Class 'Ramsey\Uuid\Uuid' not found 

### ISSUE THREAD

**Issue by jerearaujo03** [EmadAdly/laravel-uuid#5]
I'm getting this error:

```
Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Ramsey\Uuid\Uuid' not found 
in /Users/jeremias/Intranet-Bet-el/vendor/emadadly/laravel-uuid/src/Uuids.php:17
```

Why?

**Comment by jerearaujo03** [comment]
I used
`composer require ramsey/uuid`
because ramsey/rhumsaa-uuid is no longer maintained.

Can you solve this problem?

**Comment by EmadAdly** [comment]
@jerearaujo03  Let me know if this problem is resolved
However, please be aware that laravel uses the `ramsey/uuid` for generating UUID,So the package is part of laravel framework dependency. So we use it in our package.
https://github.com/laravel/framework/blob/5.4/composer.json#L28

**Comment by kushwasu** [comment]
Can we remove this package from framework dependency ?
