### ISSUE TITLE
Don't set UUID on create if it already exists

### ISSUE THREAD

**Issue by danherd** [EmadAdly/laravel-uuid#6]
I'm building an API and, as part of testing, I would like to create a resource where the UUID has been generated by the client and sent as part of the create request.

Please can you allow this functionality by not overwriting the UUID if the field is already populated?

Thanks!

**Comment by EmadAdly** [comment]
@danherd 
Users must never be able to generate their own UUID nor can they override them or  trying to change the UUID, 
This may lead to a bug in your project. I would not recommend it. 
However, you can explain to me why user entering UUID by manually may be i can to solve it better. Or as a last solution can pass your proposal as an option.

**Comment by danherd** [comment]
http://jsonapi.org/format/#crud-creating-client-ids

**Comment by danherd** [comment]
Could potentially add this check to make sure the UUID supplied is 'valid':

https://gist.github.com/joel-james/3a6201861f12a7acf4f2

**Comment by EmadAdly** [comment]
@danherd 
already have a validation uuid [LC34](https://github.com/EmadAdly/laravel-uuid/blob/master/src/Uuids.php#LC34)
Your PR is Merged

**Comment by lintburger** [comment]
@danherd @EmadAdly 
I've setup a project using 'id' as my primary key, which I've successfully setup to autogenerate UUIDs using this package. It works great when I use ::create($request->all()) in the store(Request $request) method of my controller.

I have an API use case where I want to supply the 'id' in the incoming json $request. Despite supplying it in the $request, this package generates a new UUID anyway, and stores it in the 'id' column. (I do not have 'id' in my $guarded array.) I cannot seem to set it on ::create or update it on ::update.

Is there some trick to enabling the functionality of this PR?

Model:

```
class Game extends Model
{
    use Uuids;
    public $incrementing = false;
    protected $fillable = [
        'id', 'location_id', 'gamenight_id', 'user_id', 'notes',
    ];
```

Controller:

```
public function store(Request $request)
    {
        $game = Game::create($request->all());
        return response()->json($game, 201);
    }
```

PS: thanks for your work on this!
